In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

folder_path = "/content/drive/MyDrive/원본 데이터/주민등록 1인세대수/2023년"

os.listdir(folder_path)

['2023_주민등록 1인세대수(자치구:연령별).xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-종로구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-중구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-용산구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-성동구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-광진구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-동대문구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-성북구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-강북구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-도봉구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-노원구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-은평구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-서대문구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-마포구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-양천구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-강서구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-구로구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-금천구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-영등포구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-동작구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-관악구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-서초구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-강남구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-송파구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-강동구.xlsx',
 '2023_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx']

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/원본 데이터/주민등록 1인세대수/2023년/2023_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx"

df_raw = pd.read_excel(file_path, header=None)

df_raw.head(15)

,0,1,2,3,4,5,6,7
0,※ 매년 말일자 통계 현황,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2023년,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,계,NaN,NaN,NaN,NaN,NaN
3,행정기관코드,행정기관,총 거주자수,"28,249",20~24세,25~29세,30~34세,35~39세
4,1126000000,서울특별시 중랑구,"83,528",NaN,"3,130","9,528","9,467","6,124"
5,1126052000,서울특별시 중랑구 면목제2동,"5,880","1,566",120,484,549,413
6,1126054000,서울특별시 중랑구 면목제4동,"3,862","1,040",91,356,331,262
7,1126055000,서울특별시 중랑구 면목제5동,"2,133",552,32,133,210,177
8,1126056500,서울특별시 중랑구 면목본동,"9,197","3,306",382,"1,139","1,134",651
9,1126057000,서울특별시 중랑구 면목제7동,"4,679","1,564",149,552,525,338
10,1126057500,서울특별시 중랑구 면목제3.8동,"6,201","1,961",220,644,643,454
11,1126058000,서울특별시 중랑구 상봉제1동,"3,476","1,025",73,326,360,266
12,1126059000,서울특별시 중랑구 상봉제2동,"7,903","4,473",509,"1,746","1,458",760
13,1126060000,서울특별시 중랑구 중화제1동,"3,573","1,183",105,382,425,271
14,1126061000,서울특별시 중랑구 중화제2동,"7,358","2,224",258,740,733,493

In [ ]:
header_index = df_raw[
    df_raw.apply(
        lambda row: row.astype(str).str.contains("행정기관코드").any(),
        axis=1
    )
].index[0]

header_index

# 컬럼명 4번째 줄

np.int64(3)

In [ ]:
df = pd.read_excel(file_path, header=header_index)

df.head()

       행정기관코드             행정기관  총 거주자수 28,249 20~24세 25~29세 30~34세 35~39세
0  1126000000       서울특별시 중랑구   83,528    NaN  3,130  9,528  9,467  6,124
1  1126052000  서울특별시 중랑구 면목제2동   5,880  1,566    120    484    549    413
2  1126054000  서울특별시 중랑구 면목제4동   3,862  1,040     91    356    331    262
3  1126055000  서울특별시 중랑구 면목제5동   2,133    552     32    133    210    177
4  1126056500   서울특별시 중랑구 면목본동   9,197  3,306    382  1,139  1,134    651

In [ ]:
df.columns.tolist()

['행정기관코드', '행정기관', '총 거주자수', '28,249', '20~24세', '25~29세', '30~34세', '35~39세']

In [ ]:
df.columns = (
    df.columns.astype(str)
    .str.strip()
    .str.replace("\n", "", regex=False)
    .str.replace(" ", "", regex=False)
)

df.columns.tolist()

# 줄바꿈 공백 삭제

['행정기관코드', '행정기관', '총거주자수', '28,249', '20~24세', '25~29세', '30~34세', '35~39세']

In [ ]:
df = df.rename(columns={
    '28,249': '총연령구간세대수'
})

In [ ]:
df.columns.tolist()

['행정기관코드', '행정기관', '총거주자수', '총연령구간세대수', '20~24세', '25~29세', '30~34세', '35~39세']

In [ ]:
df.columns = [
    '행정기관코드',
    '행정기관',
    '총거주자수',
    '총연령구간세대수',
    '20~24세',
    '25~29세',
    '30~34세',
    '35~39세'
]

자치구 전부 시작

2023년

In [ ]:
import glob
import os

all_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

file_list = [
    file for file in all_files
    if "-" in os.path.splitext(os.path.basename(file))[0]
]

print("전체 파일 수:", len(all_files))
print("처리 대상 파일 수:", len(file_list))

for file in file_list:
    print(os.path.basename(file))

전체 파일 수: 26
처리 대상 파일 수: 25
2023_행정동별 성연령별 주민등록 1인세대수_연간-종로구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-중구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-용산구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-성동구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-광진구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-동대문구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-성북구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-강북구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-도봉구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-노원구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-은평구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-서대문구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-마포구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-양천구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-강서구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-구로구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-금천구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-영등포구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-동작구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-관악구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-서초구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-강남구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-송파구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-강동구.xlsx
2023_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx

In [ ]:
def preprocess_single_household(file_path, year=2023):

    # 1. 원본을 헤더 없이 읽기
    raw = pd.read_excel(file_path, header=None)

    # 2. '행정기관코드'가 들어 있는 헤더 행 찾기
    header_rows = raw[
        raw.apply(
            lambda row: row.astype(str)
            .str.contains("행정기관코드", na=False)
            .any(),
            axis=1
        )
    ].index

    if len(header_rows) == 0:
        raise ValueError("행정기관코드 헤더를 찾지 못함")

    header_index = header_rows[0]

    # 3. 실제 헤더 기준으로 다시 읽기
    df = pd.read_excel(file_path, header=header_index)

    # 4. 빈 컬럼 제거
    df = df.dropna(axis=1, how="all")

    # 5. 컬럼명 공백·줄바꿈 제거
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace("\n", "", regex=False)
        .str.replace(" ", "", regex=False)
    )

    # 6. 필요한 앞 8개 컬럼만 사용
    if df.shape[1] < 8:
        raise ValueError(f"필요한 컬럼 수 부족: {df.shape[1]}개")

    df = df.iloc[:, :8].copy()

    # 구별로 합계 숫자가 컬럼명에 들어가도 강제로 통일
    df.columns = [
        "행정기관코드",
        "행정기관",
        "총거주자수",
        "총연령구간세대수",
        "20~24세",
        "25~29세",
        "30~34세",
        "35~39세"
    ]

    # 7. 행정기관코드 정리
    df["행정기관코드"] = (
        df["행정기관코드"]
        .astype(str)
        .str.replace(".0", "", regex=False)
        .str.strip()
    )

    # 엑셀 아래쪽 빈 행 제거
    df = df[
        df["행정기관코드"].notna()
        & (df["행정기관코드"] != "nan")
    ].copy()

    # 8. 숫자 컬럼 정리
    number_columns = [
        "총거주자수",
        "총연령구간세대수",
        "20~24세",
        "25~29세",
        "30~34세",
        "35~39세"
    ]

    for col in number_columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.strip()
        )

        df[col] = pd.to_numeric(df[col], errors="coerce")

    # 9. 자치구 합계행 제거
    # 예: 1126000000
    df = df[
        ~df["행정기관코드"].str.endswith("00000", na=False)
    ].copy()

    # 10. 지역명 분리
    region_split = df["행정기관"].astype(str).str.split()

    df["시도"] = region_split.str[0]
    df["자치구"] = region_split.str[1]
    df["행정동"] = region_split.str[2:].str.join(" ")

    # 11. 연도 추가
    df["연도"] = year

    # 12. 청년 1인세대수 직접 계산
    age_columns = [
        "20~24세",
        "25~29세",
        "30~34세",
        "35~39세"
    ]

    df["청년1인세대수"] = df[age_columns].sum(axis=1, min_count=1)

    # 13. 원본 합계와 직접 계산한 값 비교
    df["합계차이"] = (
        df["총연령구간세대수"]
        - df["청년1인세대수"]
    )

    # 14. 필요한 컬럼 순서 정리
    result_columns = [
        "연도",
        "행정기관코드",
        "시도",
        "자치구",
        "행정동",
        "총거주자수",
        "총연령구간세대수",
        "20~24세",
        "25~29세",
        "30~34세",
        "35~39세",
        "청년1인세대수",
        "합계차이"
    ]

    return df[result_columns]

In [ ]:
result_list = []
error_list = []

for file_path in file_list:

    try:
        temp_df = preprocess_single_household(
            file_path=file_path,
            year=2023
        )

        result_list.append(temp_df)

        print(
            "처리 완료:",
            os.path.basename(file_path),
            "/ 행 수:",
            len(temp_df)
        )

    except Exception as e:
        error_list.append({
            "파일명": os.path.basename(file_path),
            "오류": str(e)
        })

        print(
            "처리 실패:",
            os.path.basename(file_path),
            "/ 오류:",
            e
        )

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-종로구.xlsx / 행 수: 17

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-중구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-용산구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-성동구.xlsx / 행 수: 17

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-광진구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-동대문구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-성북구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-강북구.xlsx / 행 수: 13

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-도봉구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-노원구.xlsx / 행 수: 19

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-은평구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-서대문구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-마포구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-양천구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-강서구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-구로구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-금천구.xlsx / 행 수: 10

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-영등포구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-동작구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-관악구.xlsx / 행 수: 21

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-서초구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-강남구.xlsx / 행 수: 22

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-송파구.xlsx / 행 수: 27

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-강동구.xlsx / 행 수: 19
처리 완료: 2023_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx / 행 수: 16

In [ ]:
df_2023 = pd.concat(
    result_list,
    ignore_index=True
)

df_2023.head()

,연도,행정기관코드,시도,자치구,행정동,총거주자수,총연령구간세대수,20~24세,25~29세,30~34세,35~39세,청년1인세대수,합계차이
0,2023,1111051500,서울특별시,종로구,청운효자동,1898,683.0,49,185,263,186,683,0.0
1,2023,1111053000,서울특별시,종로구,사직동,2225,930.0,58,246,389,237,930,0.0
2,2023,1111054000,서울특별시,종로구,삼청동,537,158.0,13,53,54,38,158,0.0
3,2023,1111055000,서울특별시,종로구,부암동,1600,552.0,77,132,186,157,552,0.0
4,2023,1111056000,서울특별시,종로구,평창동,2140,569.0,63,125,194,187,569,0.0

In [ ]:
print("전체 행정동 수:", len(df_2023))
print("자치구 수:", df_2023["자치구"].nunique())

전체 행정동 수: 426
자치구 수: 25

In [ ]:
sorted(df_2023["자치구"].dropna().unique())

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [ ]:
error_df = pd.DataFrame(error_list)

error_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
save_path = (
    "/content/drive/MyDrive/원본 데이터/"
    "주민등록 1인세대수/"
    "전처리_결과/"
    "2023_서울시_행정동별_청년1인세대수.csv"
)

os.makedirs(
    os.path.dirname(save_path),
    exist_ok=True
)

df_2023.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", save_path)

저장 완료: /content/drive/MyDrive/원본 데이터/주민등록 1인세대수/전처리_결과/2023_서울시_행정동별_청년1인세대수.csv

In [37]:
def preprocess_year(year):

    folder_path = (
        f"/content/drive/MyDrive/원본 데이터/"
        f"주민등록 1인세대수/{year}년"
    )

    # 폴더 내 모든 엑셀 파일
    all_files = glob.glob(
        os.path.join(folder_path, "*.xlsx")
    )

    # 자치구별 파일은 파일명에 하이픈(-)이 있음
    # 서울 전체 합산 파일은 제외
    file_list = [
        file for file in all_files
        if "-" in os.path.splitext(
            os.path.basename(file)
        )[0]
    ]

    print("=" * 60)
    print(f"{year}년 전체 파일 수:", len(all_files))
    print(f"{year}년 처리 대상 파일 수:", len(file_list))

    result_list = []
    error_list = []

    for file_path in file_list:

        try:
            temp_df = preprocess_single_household(
                file_path=file_path,
                year=year
            )

            result_list.append(temp_df)

            print(
                "처리 완료:",
                os.path.basename(file_path),
                "/ 행 수:",
                len(temp_df)
            )

        except Exception as e:

            error_list.append({
                "연도": year,
                "파일명": os.path.basename(file_path),
                "오류": str(e)
            })

            print(
                "처리 실패:",
                os.path.basename(file_path),
                "/ 오류:",
                e
            )

    if len(result_list) == 0:
        raise ValueError(
            f"{year}년에 처리된 파일이 없습니다."
        )

    year_df = pd.concat(
        result_list,
        ignore_index=True
    )

    error_df = pd.DataFrame(error_list)

    print("-" * 60)
    print(f"{year}년 통합 행 수:", len(year_df))
    print(
        f"{year}년 자치구 수:",
        year_df["자치구"].nunique()
    )
    print(
        f"{year}년 실패 파일 수:",
        len(error_df)
    )

    return year_df, error_df

In [38]:
df_2024, error_2024 = preprocess_year(2024)

============================================================
2024년 전체 파일 수: 26
2024년 처리 대상 파일 수: 25

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-종로구.xlsx / 행 수: 17

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-중구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-용산구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-성동구.xlsx / 행 수: 17

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-광진구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-동대문구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-성북구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-강북구.xlsx / 행 수: 13

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-노원구.xlsx / 행 수: 19

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-은평구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-서대문구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-마포구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-양천구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-강서구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-구로구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-금천구.xlsx / 행 수: 10

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-영등포구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-동작구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-관악구.xlsx / 행 수: 21

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-서초구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-강남구.xlsx / 행 수: 22

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-송파구.xlsx / 행 수: 27
처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-도봉구.xlsx / 행 수: 14
처리 완료: 2024_행정동별 성연령별 주민등록 1인세대수_연간-강동구.xlsx / 행 수: 19
------------------------------------------------------------
2024년 통합 행 수: 426
2024년 자치구 수: 25
2024년 실패 파일 수: 0

In [39]:
df_2025, error_2025 = preprocess_year(2025)

============================================================
2025년 전체 파일 수: 26
2025년 처리 대상 파일 수: 25

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-성동구.xlsx / 행 수: 17

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-광진구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-동대문구.xlsx / 행 수: 15

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-중랑구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-성북구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-강북구.xlsx / 행 수: 13

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-도봉구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-노원구.xlsx / 행 수: 19

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-은평구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-서대문구.xlsx / 행 수: 14

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-마포구.xlsx / 행 수: 16

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-양천구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-강서구.xlsx / 행 수: 20

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-구로구.xlsx / 행 수: 16
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-금천구.xlsx / 행 수: 10

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-영등포구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-관악구.xlsx / 행 수: 21

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-서초구.xlsx / 행 수: 18

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-송파구.xlsx / 행 수: 27
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-종로구.xlsx / 행 수: 17
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-중구.xlsx / 행 수: 15
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-용산구.xlsx / 행 수: 16
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-동작구.xlsx / 행 수: 15
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-강동구.xlsx / 행 수: 19
처리 완료: 2025_행정동별 성연령별 주민등록 1인세대수_연간-강남구.xlsx / 행 수: 22
------------------------------------------------------------
2025년 통합 행 수: 427
2025년 자치구 수: 25
2025년 실패 파일 수: 0

In [40]:
save_folder = (
    "/content/drive/MyDrive/원본 데이터/"
    "주민등록 1인세대수/전처리_결과"
)

os.makedirs(
    save_folder,
    exist_ok=True
)

In [41]:
save_path_2024 = os.path.join(
    save_folder,
    "2024_서울시_행정동별_청년1인세대수.csv"
)

df_2024.to_csv(
    save_path_2024,
    index=False,
    encoding="utf-8-sig"
)

print("2024년 저장 완료:", save_path_2024)

2024년 저장 완료: /content/drive/MyDrive/원본 데이터/주민등록 1인세대수/전처리_결과/2024_서울시_행정동별_청년1인세대수.csv

In [42]:
save_path_2025 = os.path.join(
    save_folder,
    "2025_서울시_행정동별_청년1인세대수.csv"
)

df_2025.to_csv(
    save_path_2025,
    index=False,
    encoding="utf-8-sig"
)

print("2025년 저장 완료:", save_path_2025)

2025년 저장 완료: /content/drive/MyDrive/원본 데이터/주민등록 1인세대수/전처리_결과/2025_서울시_행정동별_청년1인세대수.csv

In [43]:
df_all = pd.concat(
    [
        df_2023,
        df_2024,
        df_2025
    ],
    ignore_index=True
)

df_all.head()

,연도,행정기관코드,시도,자치구,행정동,총거주자수,총연령구간세대수,20~24세,25~29세,30~34세,35~39세,청년1인세대수,합계차이
0,2023,1111051500,서울특별시,종로구,청운효자동,1898,683.0,49,185,263,186,683,0.0
1,2023,1111053000,서울특별시,종로구,사직동,2225,930.0,58,246,389,237,930,0.0
2,2023,1111054000,서울특별시,종로구,삼청동,537,158.0,13,53,54,38,158,0.0
3,2023,1111055000,서울특별시,종로구,부암동,1600,552.0,77,132,186,157,552,0.0
4,2023,1111056000,서울특별시,종로구,평창동,2140,569.0,63,125,194,187,569,0.0

In [44]:
df_all.groupby("연도").agg(
    행정동수=("행정기관코드", "count"),
    자치구수=("자치구", "nunique")
)

      행정동수  자치구수
연도
2023   426    25
2024   426    25
2025   427    25

In [45]:
save_path_all = os.path.join(
    save_folder,
    "2023_2025_서울시_행정동별_청년1인세대수.csv"
)

df_all.to_csv(
    save_path_all,
    index=False,
    encoding="utf-8-sig"
)

print("통합 파일 저장 완료:", save_path_all)

통합 파일 저장 완료: /content/drive/MyDrive/원본 데이터/주민등록 1인세대수/전처리_결과/2023_2025_서울시_행정동별_청년1인세대수.csv

In [ ]:
df_all.groupby("연도")["합계차이"].agg(
    데이터수="count",
    차이최솟값="min",
    차이최댓값="max"
)